// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiOPmBaoL4REyT7GXhdRtduBdrPKwLlnk',
    appId: '1:94303674812:web:74cfb154f6104fe641cbb9',
    messagingSenderId: '94303674812',
    projectId: 'pocketflow-dd3a8',
    authDomain: 'pocketflow-dd3a8.firebaseapp.com',
    storageBucket: 'pocketflow-dd3a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDhYT0xZ-v-hyQKBWZf_FgGniGjQU8O4',
    appId: '1:94303674812:android:00b2992262c867be41cbb9',
    messagingSenderId: '94303674812',
    projectId: 'pocketflow-dd3a8',
    storageBucket: 'pocketflow-dd3a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrE0bHGdK6BpZsPaqwXeK0ncSYGA8jWE4',
    appId: '1:94303674812:ios:9fc78130b9aab48041cbb9',
    messagingSenderId: '94303674812',
    projectId: 'pocketflow-dd3a8',
    storageBucket: 'pocketflow-dd3a8.appspot.com',
    iosClientId: '94303674812-aq3n0c0ql39rlhq902v4e917tn61rqi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrE0bHGdK6BpZsPaqwXeK0ncSYGA8jWE4',
    appId: '1:94303674812:ios:9fc78130b9aab48041cbb9',
    messagingSenderId: '94303674812',
    projectId: 'pocketflow-dd3a8',
    storageBucket: 'pocketflow-dd3a8.appspot.com',
    iosClientId: '94303674812-aq3n0c0ql39rlhq902v4e917tn61rqi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketflow',
  );
}
